# Generated by Django 4.2.1 on 2023-06-07 06:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('credit_hours', models.PositiveIntegerField(null=True)),
                ('course_level', models.PositiveIntegerField(null=True)),
                ('course_time', models.TimeField(blank=True, null=True)),
                ('course_day', models.CharField(blank=True, choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday')], max_length=1, null=True)),
                ('course_building', models.CharField(blank=True, max_length=100, null=True)),
                ('course_section', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer_name', models.CharField(max_length=100)),
                ('lecturer_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('lecturer_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{10}$')])),
                ('lecturer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('lecturer_type', models.CharField(choices=[('L', 'Laboratory'), ('T', 'Theory')], max_length=1)),
                ('lecturer_rating', models.FloatField(default=0.0)),
                ('lecturer_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.department')),
                ('lecturer_past_courses', models.ManyToManyField(blank=True, related_name='past_lecturers', to='pages.course')),
                ('lecturer_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('uni_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lab_lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_courses_taught', to='pages.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='pages.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_past_lecturers',
            field=models.ManyToManyField(blank=True, related_name='past_courses', to='pages.lecturer'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_prerequisites',
            field=models.ManyToManyField(blank=True, related_name='prerequisites', to='pages.course'),
        ),
        migrations.CreateModel(
            name='SemesterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday')], max_length=1)),
                ('start_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.lecturer')),
            ],
            options={
                'unique_together': {('course', 'lecturer', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('exam_type', models.CharField(default='Final', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
            ],
            options={
                'unique_together': {('course', 'exam_date', 'start_time')},
            },
        ),
    ]
